// <auto-generated />
using System;
using DevekoperProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevekoperProject.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevekoperProject.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<decimal>("FlatPrice")
                        .HasMaxLength(30);

                    b.Property<string>("FlatSize")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("ProjectId");

                    b.Property<string>("TotalFloor")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("BuildingId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("DevekoperProject.Models.DeveloperCompany", b =>
                {
                    b.Property<int>("DeveloperCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeveloperCompanyName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("date");

                    b.HasKey("DeveloperCompanyId");

                    b.ToTable("DeveloperCompanies");
                });

            modelBuilder.Entity("DevekoperProject.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeveloperCompanyId");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ProjectId");

                    b.HasIndex("DeveloperCompanyId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DevekoperProject.Models.Building", b =>
                {
                    b.HasOne("DevekoperProject.Models.Project", "Project")
                        .WithMany("Buildings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DevekoperProject.Models.Project", b =>
                {
                    b.HasOne("DevekoperProject.Models.DeveloperCompany", "DeveloperCompany")
                        .WithMany("Projects")
                        .HasForeignKey("DeveloperCompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
